/*
 * This file is part of the MPU6050-Library distribution (https://github.com/jmherzog-de/MPU6050-Library).
 * Copyright (c) 2021 Jean-Marcel Herzog.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/**
 *  \file mpu6050_sampleRateDivider.c
 *  \brief Sample Rate Divider
 *  
 *  This register specifies the divider from the gyroscope output rate
 *  used to generate the Sample Rate for the MPU6050.
 *  
 *  The sensor register output, FIFO output and DMP sampling are all
 *  based on the Sample Rate. The Sample Rate is generated by
 *  dividing the gyroscope output rate by SMPLRT_DIV:
 *  
 *  Sample Rate = Gyroscope Output Rate / (1 + SMPLRT_DIV)
 *  
 *  where Gyroscope Output Rate = 8 kHz when the DLPF is disabled
 *  (DLPF_CFG = 0 or 7) and 1 kHz when the DLPF is enabled
 *  (see register 26).
 *  
 *  \note The accelerometer output rate is 1 kHz. This means that for a
 *  Sample Rate greater than 1 kHz, the same accelerometer sample may be
 *  output to the FIFO, DMP and sensor registers more than once.
 *  
 *  \note For a diagram of the gyroscope and accelerometer signal paths, see
 *  Section 8 of the MPU6050 Product Specification document.
 *  
 *  \copyright Copyright 2021 Jean-Marcel Herzog. All rights reserved. This project is released under the GNU Public License.
 */

#include <stdint.h>
#include <stdbool.h>
#include "i2c.h"
#include "mpu6050_reg.h"
#include "mpu6050_sampleRateDivider.h"

/**
 *  \brief Read Sample Rate Divider register
 *  
 *  \param [in] obj Datatype pointer to return register values
 *  
 *  \details See register datasheet chapter 4.2 for more details.
 */
void mpu6050_sampleRateDividerRegRead(tMPU6050_SMPLRT_DIV *obj)
{
    *obj = i2c_receive(MPU6050_I2C_ADDR, MPU6050_SMPRT_DIV);
}

/**
 *  \brief Write Sample Rate Divider register
 *  
 *  \param [in] obj Datatype pointer to register values
 *  
 *  \details See register datasheet chapter 4.2 for more details.
 */
void mpu6050_sampleRateDividerRegWrite(tMPU6050_SMPLRT_DIV *obj)
{
    i2c_write(MPU6050_I2C_ADDR, MPU6050_SMPRT_DIV, *obj);
}